### ISSUE TITLE
Should be called 'magnet-scanner-android'?

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-scanner-android#1]
If this library is only usable on Android I feel we should make it clear in the title

**Comment by wilsonpage** [comment]
Sorry this is a bit NITTY of me 😱

**Comment by arcturus** [comment]
Actually yes, as it uses android libraries.

**Comment by wilsonpage** [comment]
Renamed github repo. I think the classes themselves should be renamed to reflect the project name:

`Scanner` -> `MagnetScanner`

etc

**Comment by arcturus** [comment]
Not the repo, I agree on renaming the class `Scanner` but the repo name is ok, as we should have a different repo for the swift library.

**Comment by wilsonpage** [comment]
@arcturus you already agreed on the rename of the repo [above](https://github.com/mozilla-magnet/magnet-scanner-android/issues/1#issuecomment-220604206), so that's been done. If/when we make an ios equivalent, it should be called `magnet-scanner-ios` not `magnet-scanner-swift`.

The libraries have a hard dependency on a specific platform, the language they are written in is irrelevant.

**Comment by arcturus** [comment]
That's totally right, and yes, more sense as I said myself, it's not pure java, it uses android classes so ...
