### ISSUE TITLE
.useBTLE() and usemDNS() require an argument for testing 

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-scanner-android#4]
Android studio is complaining that a required argument is not being provided to [`.useBTLE()`](https://github.com/mozilla-magnet/magnet-scanner-android/blob/master/src/main/java/org/mozilla/magnet/net/scanner/Scanner.java#L54) and [`.usemDNS()`](https://github.com/mozilla-magnet/magnet-scanner-android/blob/master/src/main/java/org/mozilla/magnet/net/scanner/Scanner.java#L69) methods. Perhaps these mocks should be passed in elsewhere?

**Comment by wilsonpage** [comment]
@arcturus what do you suggest?

**Comment by wilsonpage** [comment]
Passing `null` seems to be a temporary workaround.

**Comment by arcturus** [comment]
Yes it is.
Actually those functions didn't require at the begining any parameter, but when doing the unit tests we passed as a dependency a mock of each scanner.

**Comment by wilsonpage** [comment]
Are you suggesting this is a WONTFIX, or should we provide an alternative means of providing mocks that doesn't pollute the function signature?

**Comment by arcturus** [comment]
TBH, I would I'd like a better solution on the testing side, that doesn't pollutes the signature.

**Comment by wilsonpage** [comment]
Fixed by b5de3f4461041cfbb5b67a4a38f17d13bf2668bd
